import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { AppProvider } from "#components/AppProvider";
import { Footer } from "#components/Footer";
import { Navbar } from "#components/Navbar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Is X Maintained?",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  const nonce = headers().get("x-nonce") ?? undefined;

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider nonce={nonce}>
          <Navbar />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
};

export default RootLayout;
